# Generated by Django 6.0.4 on 2026-05-01 21:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0004_league'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('startYear', models.IntegerField()),
                ('endYear', models.IntegerField()),
            ],
        ),
    ]
