# Generated by Django 6.0.4 on 2026-05-02 21:12

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0005_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='season',
            name='endYear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1001, 'Jahreszahl muss valid sein.'), django.core.validators.MaxValueValidator(2027, 'Jahreszahl ist zu gross.')]),
        ),
        migrations.AlterField(
            model_name='season',
            name='startYear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1001, 'Jahreszahl muss valid sein.'), django.core.validators.MaxValueValidator(2027, 'Jahreszahl ist zu gross.')]),
        ),
    ]
