# Generated by Django 6.0.4 on 2026-05-02 21:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0006_person_alter_season_endyear_alter_season_startyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
