# Generated by Django 6.0.4 on 2026-05-02 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0007_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonClub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('captains', models.ManyToManyField(blank=True, related_name='captain_season_clubs', to='trikots.person')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.club')),
                ('presidents', models.ManyToManyField(blank=True, related_name='president_season_clubs', to='trikots.person')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.season')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trikots.supplier')),
                ('trainers', models.ManyToManyField(blank=True, related_name='trainer_season_clubs', to='trikots.person')),
            ],
        ),
    ]
