# Generated by Django 6.0.4 on 2026-05-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0008_seasonclub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonclub',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
