# Generated by Django 6.0.4 on 2026-05-04 21:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0009_alter_seasonclub_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goals_home', models.IntegerField()),
                ('goals_away', models.IntegerField()),
                ('date', models.DateField()),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_club', to='trikots.club')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_club', to='trikots.club')),
            ],
        ),
    ]
