# Generated by Django 6.0.4 on 2026-05-04 21:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0010_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goal_scorers',
            field=models.ManyToManyField(blank=True, related_name='goal_scorer', to='trikots.person'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_away',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Das Resultat muss positiv sein.')]),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_home',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Das Resultat muss positiv sein.')]),
        ),
    ]
