# Generated by Django 6.0.4 on 2026-05-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0011_match_goal_scorers_alter_match_goals_away_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_person_full_name'),
        ),
    ]
