# Generated by Django 6.0.4 on 2026-05-04 21:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0012_person_unique_person_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('image', models.ImageField(upload_to='shirt_images')),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('match_worn', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.club')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.person')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.season')),
            ],
        ),
    ]
