# Generated by Django 6.0.4 on 2026-05-04 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0013_shirt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trikots.match'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trikots.person'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
