# Generated by Django 6.0.4 on 2026-05-07 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0014_alter_shirt_match_alter_shirt_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Club', 'verbose_name_plural': 'Clubs'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Land', 'verbose_name_plural': 'Länder'},
        ),
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'Liga', 'verbose_name_plural': 'Ligen'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Spiel', 'verbose_name_plural': 'Spiele'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Personen'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Saison', 'verbose_name_plural': 'Saisons'},
        ),
        migrations.AlterModelOptions(
            name='seasonclub',
            options={'verbose_name': 'Saison-Club', 'verbose_name_plural': 'Saison-Clubs'},
        ),
        migrations.AlterModelOptions(
            name='shirt',
            options={'verbose_name': 'Trikot', 'verbose_name_plural': 'Trikots'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Ausrüster', 'verbose_name_plural': 'Ausrüster'},
        ),
        migrations.AddField(
            model_name='season',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trikots.league', verbose_name='Liga'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.country', verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.country', verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_club', to='trikots.club', verbose_name='Auswärtsclub'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goal_scorers',
            field=models.ManyToManyField(blank=True, related_name='goal_scorer', to='trikots.person', verbose_name='Torschützen'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_away',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Das Resultat muss positiv sein.')], verbose_name='Tore Auswärtsclub'),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_home',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Das Resultat muss positiv sein.')], verbose_name='Tore Heimclub'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_club', to='trikots.club', verbose_name='Heimclub'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nachname'),
        ),
        migrations.AlterField(
            model_name='season',
            name='endYear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1001, 'Jahreszahl muss valid sein.'), django.core.validators.MaxValueValidator(2027, 'Jahreszahl ist zu gross.')], verbose_name='Jahr der Rückrunde'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Bezeichnung (Prefix)'),
        ),
        migrations.AlterField(
            model_name='season',
            name='startYear',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1001, 'Jahreszahl muss valid sein.'), django.core.validators.MaxValueValidator(2027, 'Jahreszahl ist zu gross.')], verbose_name='Jahr der Vorrunde'),
        ),
        migrations.AlterField(
            model_name='seasonclub',
            name='captains',
            field=models.ManyToManyField(blank=True, related_name='captain_season_clubs', to='trikots.person', verbose_name='Käptain/(-e)'),
        ),
        migrations.AlterField(
            model_name='seasonclub',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='seasonclub',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='seasonclub',
            name='presidents',
            field=models.ManyToManyField(blank=True, related_name='president_season_clubs', to='trikots.person', verbose_name='Präsident/(-e)'),
        ),
        migrations.AlterField(
            model_name='seasonclub',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.season', verbose_name='Saison'),
        ),
        migrations.AlterField(
            model_name='seasonclub',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trikots.supplier', verbose_name='Ausrüster'),
        ),
        migrations.AlterField(
            model_name='seasonclub',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='trainer_season_clubs', to='trikots.person', verbose_name='Trainer/(-innen)'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.club', verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='image',
            field=models.ImageField(upload_to='shirt_images', verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trikots.match', verbose_name='Spiel'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='match_worn',
            field=models.BooleanField(default=False, verbose_name='Matchworn'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trikotnummer'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trikots.person', verbose_name='Spieler'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Preis'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Kaufdatum'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trikots.season', verbose_name='Saison'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
