# Generated by Django 6.0.4 on 2026-05-20 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0015_alter_club_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shirt',
            name='image',
        ),
        migrations.AddField(
            model_name='shirt',
            name='image_back',
            field=models.ImageField(blank=True, null=True, upload_to='shirts_DEV/', verbose_name='Rückseite'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='image_front',
            field=models.ImageField(default='', upload_to='shirts_DEV/', verbose_name='Vorderseite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seasonclub',
            name='captains',
            field=models.ManyToManyField(blank=True, related_name='captain_season_clubs', to='trikots.person', verbose_name='Kaptains'),
        ),
        migrations.AlterField(
            model_name='seasonclub',
            name='presidents',
            field=models.ManyToManyField(blank=True, related_name='president_season_clubs', to='trikots.person', verbose_name='Präsidenten'),
        ),
        migrations.AlterField(
            model_name='seasonclub',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='trainer_season_clubs', to='trikots.person', verbose_name='Trainer'),
        ),
    ]
