# Generated by Django 6.0.4 on 2026-05-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0016_remove_shirt_image_shirt_image_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round_of_League',
            field=models.IntegerField(blank=True, null=True, verbose_name='Runde der Liga'),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Uhrzeit'),
        ),
        migrations.AddField(
            model_name='match',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
