# Generated by Django 5.2.14 on 2026-05-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0017_match_round_of_league_match_time_match_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='url',
            new_name='highlight_url',
        ),
    ]
