# Generated by Django 5.2.14 on 2026-05-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0018_rename_url_match_highlight_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='is_goal_keeper_shirt',
            field=models.BooleanField(default=False, verbose_name='Torwarttrikot'),
        ),
        migrations.AddField(
            model_name='shirt',
            name='type',
            field=models.CharField(blank=True, choices=[('HOME', 'Heimtrikot'), ('AWAY', 'Auswärtstrikot'), ('SPECIAL', 'Special Edition')], null=True, verbose_name='Trikottyp'),
        ),
        migrations.AlterField(
            model_name='match',
            name='highlight_url',
            field=models.URLField(blank=True, null=True, verbose_name='Highlight URL'),
        ),
    ]
