# Generated by Django 5.2.14 on 2026-05-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0019_shirt_is_goal_keeper_shirt_shirt_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shirt',
            old_name='type',
            new_name='shirt_type',
        ),
    ]
