# Generated by Django 5.2.14 on 2026-05-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trikots', '0020_rename_type_shirt_shirt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='shirt_type',
            field=models.CharField(choices=[('HOME', 'Heimtrikot'), ('AWAY', 'Auswärtstrikot'), ('SPECIAL', 'Special Edition')], default='HOME', verbose_name='Trikottyp'),
            preserve_default=False,
        ),
    ]
